In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import os
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
#data collection and processing

movies_data = pd.read_csv('movies.csv')
movies_data

index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction   
1         1  300000000                  Adventure Fantasy Action   
2         2  245000000                    Action Adventure Crime   
3         3  250000000               Action Crime Drama Thriller   
4         4  260000000          Action Adventure Science Fiction   
...     ...        ...                                       ...   
4798   4798     220000                     Action Crime Thriller   
4799   4799       9000                            Comedy Romance   
4800   4800          0             Comedy Drama Romance TV Movie   
4801   4801          0                                       NaN   
4802   4802          0                               Documentary   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     culture clash future space war space colony so...                en   
1     ocean drug abuse exotic island east india trad...                en   
2            spy based on novel secret agent sequel mi6                en   
3     dc comics crime fighter terrorist secret ident...                en   
4     based on novel mars medallion space travel pri...                en   
...                                                 ...               ...   
4798  united states\u2013mexico barrier legs arms pa...                es   
4799                                                NaN                en   
4800  date love at first sight narration investigati...                en   
4801                                                NaN                en   
4802               obsession camcorder crush dream girl                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2     A cryptic message from Bond’s past sends him o...  107.376788  ...   
3     Following the death of District Attorney Harve...  112.312950  ...   
4     John Carter is a war-weary, former military ca...   43.926995  ...   
...                                                 ...         ...  ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...   
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...   
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...   
4802  Ever since the s

In [6]:
movies_data.shape

(4803, 24)

In [7]:
#selecting relevent features

selected_features = ['genres','keywords','tagline','cast','director','original_language','overview']
selected_features

['genres',
 'keywords',
 'tagline',
 'cast',
 'director',
 'original_language',
 'overview']

In [8]:
#replacing the null values

for feature in selected_features:
    movies_data[feature] = movies_data[feature].fillna('')

In [12]:
#combining the columns

combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+ movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']+' '+movies_data['original_language']+' '+movies_data['overview']

In [13]:
combined_features

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [14]:
#coverting to the vectors

vectorizer = TfidfVectorizer()

In [16]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [17]:
print(feature_vectors)

  (0, 5247)	0.16501006775547178
  (0, 1015)	0.12281483475578292
  (0, 1244)	0.052688384272339364
  (0, 21531)	0.16644197206569722
  (0, 1282)	0.03194056277386936
  (0, 19657)	0.16114836117475895
  (0, 10373)	0.1384336281545381
  (0, 2976)	0.09970589210080175
  (0, 27530)	0.14564049713224922
  (0, 2687)	0.09801861855221852
  (0, 4131)	0.06193539266210169
  (0, 18030)	0.10935524187822071
  (0, 28612)	0.15485255642963552
  (0, 19548)	0.04906580238586929
  (0, 18254)	0.1476456874519244
  (0, 27420)	0.03100401179862503
  (0, 7831)	0.17973500853712363
  (0, 14028)	0.04167600071036139
  (0, 17026)	0.143194506489404
  (0, 20111)	0.19253195938485537
  (0, 4770)	0.12497113327809026
  (0, 239)	0.197099388840671
  (0, 13479)	0.036465463446112366
  (0, 8926)	0.02665578026167305
  (0, 4290)	0.13208435165943985
  :	:
  (4802, 19250)	0.06134088052640477
  (4802, 11946)	0.07828093766187212
  (4802, 29695)	0.07734470758484706
  (4802, 9350)	0.07103332353189366
  (4802, 19490)	0.05756631608304895
  (4802

In [18]:
similarity = cosine_similarity(feature_vectors)

In [19]:
print(similarity)

[[1.         0.05148617 0.03392811 ... 0.02801039 0.03099337 0.00770394]
 [0.05148617 1.         0.04417805 ... 0.05125681 0.03149969 0.01564774]
 [0.03392811 0.04417805 1.         ... 0.02694306 0.04797411 0.01414021]
 ...
 [0.02801039 0.05125681 0.02694306 ... 1.         0.03518829 0.03579459]
 [0.03099337 0.03149969 0.04797411 ... 0.03518829 1.         0.03130853]
 [0.00770394 0.01564774 0.01414021 ... 0.03579459 0.03130853 1.        ]]


In [20]:
similarity.shape

(4803, 4803)

In [21]:
#similarity will give some similarity value by which we will be getting a similarity score
#it will compare eg avatar to all the other movies accordingly

In [27]:
movie = input('enter your favourite movie name : ')

enter your favourite movie name : iron man


In [24]:
#creating the list which contains all the movie titles present in data set

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [28]:
#here we will find the close match for the movie privided by user

find_close_match = difflib.get_close_matches(movie, list_of_all_titles)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [29]:
close_match = find_close_match[0]
print(close_match)

Iron Man


In [30]:
#finding the movie index with help of title

index_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_movie)

68


In [32]:
#getting a list of similar movies

sim_score = list(enumerate(similarity[index_movie]))
print(sim_score)

[(0, 0.05083893409016364), (1, 0.03716124266452726), (2, 0.011666622125149337), (3, 0.007065208444118491), (4, 0.026810673037329275), (5, 0.014937662548823704), (6, 0.033275097510479544), (7, 0.19387577136079417), (8, 0.011150025778084528), (9, 0.03714009111727032), (10, 0.03913959010029088), (11, 0.013666002661827157), (12, 0.011200401141530363), (13, 0.010982692323718322), (14, 0.05885574506267876), (15, 0.02897859649449168), (16, 0.13262794885241017), (17, 0.016309152117409003), (18, 0.021219276416786153), (19, 0.042881868818267325), (20, 0.03716728615123053), (21, 0.02503545711442251), (22, 0.009800047555443829), (23, 0.018281436551421955), (24, 0.01855705525872456), (25, 0.0038761939173283587), (26, 0.1161694271291082), (27, 0.03351049695738133), (28, 0.03784802332489709), (29, 0.010035475453279534), (30, 0.08022661555648156), (31, 0.29103814965137403), (32, 0.02617644060304284), (33, 0.07834291234956449), (34, 0.006557033170460637), (35, 0.021662176706434246), (36, 0.025798892491

In [33]:
#now after getting the sim score for all the movies 
#its time to recommend more similar movies to the user 

In [35]:
sorted_similar_movies = sorted(sim_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(68, 1.0000000000000002), (79, 0.3296378318196148), (31, 0.29103814965137403), (7, 0.19387577136079417), (16, 0.13262794885241017), (4401, 0.11927686124340056), (511, 0.11797878533982761), (26, 0.1161694271291082), (64, 0.11326362388763227), (182, 0.10863636266223912), (3623, 0.10498977034596504), (94, 0.10069283807574861), (46, 0.08869856707974016), (4033, 0.08718643334213297), (783, 0.0869877309280045), (174, 0.08652876117743809), (618, 0.08467939038428837), (85, 0.08358063837585118), (3133, 0.08054168374039268), (101, 0.08051837756387765), (1740, 0.08037545226989534), (30, 0.08022661555648156), (3466, 0.07912166868722419), (33, 0.07834291234956449), (203, 0.07767268316867439), (1177, 0.07721723535766267), (420, 0.07711865054993461), (131, 0.07577573725671409), (1406, 0.07570968036377682), (318, 0.07509831193636846), (788, 0.07435216695109356), (2229, 0.07429490666540578), (122, 0.07389477676326056), (1135, 0.07357295909022865), (2235, 0.07322277804308294), (138, 0.073059643188419),

In [37]:
print('You may also like : \n')

i = 1
for movies in sorted_similar_movies:
    index = movies[0]
    title_from_index = movies_data[movies_data.index == index]['title'].values[0]
    if (i<16):
        print(i,'.',title_from_index)
        i+=1

You may also like : 

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . The Avengers
6 . The Helix... Loaded
7 . X-Men
8 . Captain America: Civil War
9 . X-Men: Apocalypse
10 . Ant-Man
11 . Made
12 . Guardians of the Galaxy
13 . X-Men: Days of Future Past
14 . Super
15 . Mortdecai


In [38]:
#just pasted the above code together so it will process alltogether

movie = input('enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie, list_of_all_titles)

close_match = find_close_match[0]

index_movie = movies_data[movies_data.title == close_match]['index'].values[0]

sim_score = list(enumerate(similarity[index_movie]))

sorted_similar_movies = sorted(sim_score, key = lambda x:x[1], reverse = True)

print('You may also like : \n')

i = 1

for movies in sorted_similar_movies:
    index = movies[0]
    title_from_index = movies_data[movies_data.index == index]['title'].values[0]
    if (i<16):
        print(i,'.',title_from_index)
        i+=1

enter your favourite movie name : batman
You may also like : 

1 . Batman
2 . Batman Returns
3 . Batman Begins
4 . Batman & Robin
5 . The Dark Knight Rises
6 . The Dark Knight
7 . Batman: The Dark Knight Returns, Part 2
8 . Batman Forever
9 . Batman v Superman: Dawn of Justice
10 . Spider-Man 2
11 . Suicide Squad
12 . Chill Factor
13 . Green Lantern
14 . Superman
15 . A History of Violence
