In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [4]:
#data collection

#loading data through csv file into pandas dataframe

dataset = pd.read_csv('mail_data.csv')
dataset

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
dataset.shape

(5572, 2)

In [7]:
dataset.isnull().sum()

Category    0
Message     0
dtype: int64

In [10]:
dataset1 = dataset.where((pd.notnull(dataset)),'')

In [11]:
dataset1.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [13]:
dataset1['Category'].unique()

array(['ham', 'spam'], dtype=object)

In [14]:
#label encoding

#spam 1 and ham 0

#we can use label Encoder from prepro
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
dataset1['Category']= label_encoder.fit_transform(dataset1['Category'])



#one more type of doing encoding
#dataset1.loc[dataset['Category'] == 'spam' , 'Category',] = 0
#dataset1.loc[dataset['Category'] == 'ham' , 'Category',] = 1

In [16]:
dataset1['Category'].unique()

array([0, 1])

In [18]:
X = dataset1['Message']
y = dataset1['Category']

In [19]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [20]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Category, Length: 5572, dtype: int32

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=5)

In [22]:
X_train.shape

(3733,)

In [23]:
X_test.shape

(1839,)

In [24]:
#feature extraction

feature_extraction = TfidfVectorizer(min_df = 1, stop_words = 'english', lowercase = 'True')

X_train_features = feature_extraction.fit_transform(X_train)

#we dont want to show thr test data to ou machine so we dont apply fit_transform in there

X_test_features = feature_extraction.transform(X_test)

y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [26]:
print(X_train_features)

  (0, 2806)	0.7059699736776629
  (0, 1679)	0.7082417639941605
  (1, 2858)	0.27410785873564353
  (1, 3735)	0.2737001810914417
  (1, 5256)	0.48223642568625646
  (1, 969)	0.33881319089275186
  (1, 3586)	0.3481263807494109
  (1, 1477)	0.48223642568625646
  (1, 1170)	0.3858274184605698
  (2, 1946)	0.4783893621709066
  (2, 5263)	0.3152460174149978
  (2, 3166)	0.4159688499853424
  (2, 4285)	0.5677556658962867
  (2, 2858)	0.29719481816441995
  (2, 3735)	0.2967528035359553
  (3, 5994)	0.2581192900615116
  (3, 931)	0.3417835847546658
  (3, 4808)	0.4080900960668566
  (3, 5519)	0.38869668473121927
  (3, 5996)	0.22763879882730223
  (3, 2684)	0.3150171406184831
  (3, 2206)	0.4080900960668566
  (3, 3077)	0.3749368404107612
  (3, 3609)	0.20190441213963414
  (4, 3541)	0.6356624392126645
  :	:
  (3730, 2682)	0.5434151446187039
  (3730, 4366)	0.517590765328012
  (3730, 3231)	0.517590765328012
  (3730, 2784)	0.41097394064996257
  (3731, 4572)	0.5618916275575488
  (3731, 5081)	0.5618916275575488
  (3731, 3

In [27]:
#training

lr = LogisticRegression()

lr.fit(X_train_features,y_train)

LogisticRegression()

In [28]:
y_train_pred = lr.predict(X_train_features)

y_test_pred = lr.predict(X_test_features)

In [32]:
print('Accuracy_score_training : ',accuracy_score(y_train_pred,y_train))

Accuracy_score_training :  0.9654433431556388


In [33]:
y_train_pred

array([0, 0, 0, ..., 0, 0, 0])

In [35]:
print('confusion matrix training : \n',confusion_matrix(y_train_pred,y_train))

confusion matrix training : 
 [[3228  127]
 [   2  376]]


In [36]:
print('Accuracy_score_testing : ',accuracy_score(y_test_pred,y_test))

Accuracy_score_training :  0.957041870581838


In [37]:
print('confusion matrix testing : \n',confusion_matrix(y_test_pred,y_test))

confusion matrix testing : 
 [[1594   78]
 [   1  166]]


In [44]:
input_mail = ["Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."]

input_mail_feature = feature_extraction.transform(input_mail)

prediction = lr.predict(input_mail_feature)
print(prediction)

#print(input_mail)

if prediction[0] == 1:
    print('The mail is spam \n')
else:
    print('The mail is not spam')
    

[0]
The mail is not spam


In [40]:
dataset1.head(15)

Category                                            Message
0          0  Go until jurong point, crazy.. Available only ...
1          0                      Ok lar... Joking wif u oni...
2          1  Free entry in 2 a wkly comp to win FA Cup fina...
3          0  U dun say so early hor... U c already then say...
4          0  Nah I don't think he goes to usf, he lives aro...
5          1  FreeMsg Hey there darling it's been 3 week's n...
6          0  Even my brother is not like to speak with me. ...
7          0  As per your request 'Melle Melle (Oru Minnamin...
8          1  WINNER!! As a valued network customer you have...
9          1  Had your mobile 11 months or more? U R entitle...
10         0  I'm gonna be home soon and i don't want to tal...
11         1  SIX chances to win CASH! From 100 to 20,000 po...
12         1  URGENT! You have won a 1 week FREE membership ...
13         0  I've been searching for the right words to tha...
14         0                I HAVE A DATE ON SUNDAY WITH WILL!!